import { useEffect, useState } from "react";

export default function ModuleModal({ isOpen, onClose, module, onSave }) {
  const [formData, setFormData] = useState({
    moduleCode: "",
    moduleName: "",
    department: "",
    primaryLecturer: "",
    sessionsPerWeek: "",
    sessionTypes: [],
    status: "Active",
  });

  useEffect(() => {
    if (module) {
      setFormData(module);
    } else {
      setFormData({
        moduleCode: "",
        moduleName: "",
        department: "",
        primaryLecturer: "",
        sessionsPerWeek: "",
        sessionTypes: [],
        status: "Active",
      });
    }
  }, [module]);

  if (!isOpen) return null;

 const handleChange = (e) => {
   const { name, value } = e.target;

   setFormData({
     ...formData,

     [name]: value,

     ...(name === "department" && {
       moduleCode: generateModuleCode(value),
     }),
   });
 };

  const handleTypeChange = (type) => {
    setFormData({
      ...formData,

      sessionTypes: formData.sessionTypes.includes(type)
        ? formData.sessionTypes.filter((item) => item !== type)
        : [...formData.sessionTypes, type],
    });
  };
  const generateModuleCode = (department) => {
    const prefix = {
      Computing: "IT",

      Engineering: "EN",

      Business: "BM",

      Management: "MG",
    };

    const code = prefix[department] || "MD";

    const number = Math.floor(Math.random() * 9000) + 1000;

    return `${code}${number}`;
  };

  return (
    <div
      className="
      fixed
      inset-0
      bg-black/40
      flex
      items-center
      justify-center
      z-50
      "
    >
      <div
        className="
        bg-white
        w-[500px]
        rounded-lg
        shadow-lg
        "
      >
        {/* Header */}

        <div
          className="
          px-5
          py-4
          border-b
          flex
          justify-between
          "
        >
          <h2
            className="
            font-semibold
            text-slate-900
            "
          >
            {module ? "Edit Module" : "Add Module"}
          </h2>

          <button onClick={onClose} className="text-slate-500">
            ✕
          </button>
        </div>

        {/* Form */}

        <div
          className="
          p-5
          space-y-4
          "
        >
          <div>
            <label className="text-sm text-slate-600">Module Code</label>

            <input
              value={formData.moduleCode}
              readOnly
              className="
w-full
border
rounded-lg
px-3
py-2
mt-1
bg-gray-100
text-slate-500
"
            />

            <p
              className="
text-xs
text-slate-400
mt-1
"
            >
              Auto generated by system
            </p>
          </div>

          <div>
            <label className="text-sm">Module Name</label>

            <input
              name="moduleName"
              value={formData.moduleName}
              onChange={handleChange}
              placeholder="Software Engineering"
              className="
              w-full
              border
              rounded-lg
              px-3
              py-2
              mt-1
              "
            />
          </div>

          <div>
            <label className="text-sm">Department</label>

            <select
              name="department"
              value={formData.department}
              onChange={handleChange}
              className="
              w-full
              border
              rounded-lg
              px-3
              py-2
              mt-1
              "
            >
              <option value="">Select Department</option>

              <option>Computing</option>

              <option>Engineering</option>

              <option>Business</option>

              <option>Management</option>
            </select>
          </div>

          <div>
            <label className="text-sm">Primary Lecturer</label>

            <input
              name="primaryLecturer"
              value={formData.primaryLecturer}
              onChange={handleChange}
              placeholder="Dr. N. Perera"
              className="
              w-full
              border
              rounded-lg
              px-3
              py-2
              mt-1
              "
            />
          </div>

          <div>
            <label className="text-sm">Sessions Per Week</label>

            <input
              type="number"
              name="sessionsPerWeek"
              value={formData.sessionsPerWeek}
              onChange={handleChange}
              className="
              w-full
              border
              rounded-lg
              px-3
              py-2
              mt-1
              "
            />
          </div>

          <div>
            <label className="text-sm">Session Types</label>

            <div
              className="
              flex
              gap-4
              mt-2
              "
            >
              {["Lecture", "Lab", "Tutorial", "Practical"].map((type) => (
                <label
                  key={type}
                  className="
                    flex
                    items-center
                    gap-2
                    text-sm
                    "
                >
                  <input
                    type="checkbox"
                    checked={formData.sessionTypes.includes(type)}
                    onChange={() => handleTypeChange(type)}
                  />

                  {type}
                </label>
              ))}
            </div>
          </div>

          <div>
            <label className="text-sm">Status</label>

            <select
              name="status"
              value={formData.status}
              onChange={handleChange}
              className="
              w-full
              border
              rounded-lg
              px-3
              py-2
              mt-1
              "
            >
              <option>Active</option>

              <option>Inactive</option>
            </select>
          </div>
        </div>

        {/* Footer */}

        <div
          className="
          px-5
          py-4
          border-t
          flex
          justify-end
          gap-3
          "
        >
          <button
            onClick={onClose}
            className="
            px-4
            py-2
            border
            rounded-lg
            text-sm
            "
          >
            Cancel
          </button>

          <button
            onClick={() => onSave(formData)}
            className="
            px-4
            py-2
            bg-[#0b1220]
            text-white
            rounded-lg
            text-sm
            "
          >
            Save Module
          </button>
        </div>
      </div>
    </div>
  );
}
